# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='playlist',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='playlists.Playlist'),
            preserve_default=False,
        ),
    ]
